### PR TITLE
fix conflicts in PR More commands and Order

### PR DESCRIPTION
**Pull request by darlanmendonca**
a merged from https://github.com/darlanmendonca/bash-basics/pull/6

### CODE REVIEW

**Comment by darlanmendonca** [comment]
@khaosdoctor I accept the @WendellAdriel PR, and make a merge with your.

Can u give me a OK, if has all right after merge please?

Then we merge all :D

**Comment by khaosdoctor** [comment]
I believe the order is still off, some commands are out of order

**Review by khaosdoctor — APPROVED** [review]
Double checking this, I think it is Ok

**Comment by darlanmendonca** [comment]
So, lets merge, and create a new issue to define order :D

**Comment by khaosdoctor** [comment]
I applied that order we were talking about on #3, except for Wendell's parts, which came a bit later so I just reordered them accordingly 😅

**Comment by darlanmendonca** [comment]
oh, nice

**Pull request merged**
